install.packages('tidyverse')
install.packages('igraph')
install.packages('magrittr')
install.packages('tidyverse')
install.packages('magrittr')
install.packages('tictoc')
install.packages('broom')
install.packages('igraph')
install.packages('tidygraph')
install.packages('viridis')
install.packages('ggraph')
install.packages('ggrepel')
install.packages('gridExtra')
install.packages('graphlayouts')
install.packages('assortnet') # Assortativity Analysis